\documentclass[12pt]{article}
\usepackage{Sweave}
\usepackage{myVignette}
\usepackage[authoryear,round]{natbib}
\bibliographystyle{plainnat}
\DefineVerbatimEnvironment{Sinput}{Verbatim}
{formatcom={\vspace{-2.5ex}},fontshape=sl,
  fontfamily=courier,fontseries=b, fontsize=\scriptsize}
\DefineVerbatimEnvironment{Soutput}{Verbatim}
{formatcom={\vspace{-2.5ex}},fontfamily=courier,fontseries=b,%
  fontsize=\scriptsize}
%%\VignetteIndexEntry{Examples from Multilevel Software Reviews}
%%\VignetteDepends{lme4}
\begin{document}

\setkeys{Gin}{width=\textwidth}
\title{Examples from Multilevel Software Comparative Reviews}
\author{Douglas Bates\\R Development Core Team\\\email{Douglas.Bates@R-project.org}}
\date{\today}
\maketitle
\begin{abstract}
   The Center for Multilevel Modelling at the Institute of Education,
   London maintains a web site of ``Software reviews of multilevel
   modeling packages''.  The data sets discussed in the reviews are
   available at this web site.  We have incorporated these data sets
   in the \code{lme4} package for \RR{} and, in this vignette, provide
   the results of fitting several models to these data sets.
\end{abstract}

\section{Introduction}
\label{sec:Intro}


\section{Two-level normal models}
\label{sec:TwoLevelNormal}



The \code{Exam} data set is used in fitting examples of two-level
normal multilevel models.

\begin{Schunk}
\begin{Sinput}
> str(Exam)
\end{Sinput}
\begin{Soutput}
`data.frame':	4059 obs. of  10 variables:
 $ school  : Factor w/ 65 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ normexam: num   0.261  0.134 -1.724  0.968  0.544 ...
 $ schgend : Factor w/ 3 levels "mixed","boys",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ schavg  : num  0.166 0.166 0.166 0.166 0.166 ...
 $ vr      : Factor w/ 3 levels "bottom 25%","mid 50%",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ intake  : Factor w/ 3 levels "bottom 25%","mid 50%",..: 1 2 3 2 2 1 3 2 2 3 ...
 $ standLRT: num   0.619  0.206 -1.365  0.206  0.371 ...
 $ sex     : Factor w/ 2 levels "F","M": 1 1 2 1 1 2 2 2 1 2 ...
 $ type    : Factor w/ 2 levels "Mxd","Sngl": 1 1 1 1 1 1 1 1 1 1 ...
 $ student : Factor w/ 650 levels "1","2","3","4",..: 143 145 142 141 138 155 158 115 117 113 ...
\end{Soutput}
\begin{Sinput}
> system.time(Em1 <- lmer(normexam ~ standLRT + sex + schgend + 
+     (1 | school), Exam), gc = TRUE)
\end{Sinput}
\begin{Soutput}
[1] 0.15 0.01 0.15 0.00 0.00
\end{Soutput}
\begin{Sinput}
> summary(Em1)
\end{Sinput}
\begin{Soutput}
Linear mixed-effects model fit by REML
Formula: normexam ~ standLRT + sex + schgend + (1 | school) 
   Data: Exam 
      AIC      BIC    logLik deviance REMLdeviance
 9361.673 9405.834 -4673.837 9325.501     9347.673
Random effects:
 Groups   Name        Variance Std.Dev.
 school   (Intercept) 0.085829 0.29297 
 Residual             0.562534 0.75002 
# of obs: 4059, groups: school, 65

Fixed effects:
                Estimate  Std. Error   DF t value  Pr(>|t|)
(Intercept)  -1.0493e-03  5.5569e-02 4054 -0.0189   0.98494
standLRT      5.5975e-01  1.2450e-02 4054 44.9601 < 2.2e-16
sexM         -1.6739e-01  3.4100e-02 4054 -4.9089 9.519e-07
schgendboys   1.7769e-01  1.1347e-01 4054  1.5659   0.11745
schgendgirls  1.5900e-01  8.9403e-02 4054  1.7784   0.07541

Correlation of Fixed Effects:
            (Intr) stnLRT sexM   schgndb
standLRT    -0.014                      
sexM        -0.316  0.061               
schgendboys -0.395 -0.003 -0.145        
schgendgrls -0.622  0.009  0.197  0.245 
\end{Soutput}
\end{Schunk}

There are some interesting aspects of data management that show up in
the analysis of these data.  The \code{student} variable is an
identifier of the student within the \code{school}.  It would be best
to combine the indicators of school and student to get a unique
identifier of the student.

\begin{Schunk}
\begin{Sinput}
> Exam$ids <- with(Exam, school:student)[, drop = TRUE]
> str(Exam)
\end{Sinput}
\begin{Soutput}
`data.frame':	4059 obs. of  11 variables:
 $ school  : Factor w/ 65 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ normexam: num   0.261  0.134 -1.724  0.968  0.544 ...
 $ schgend : Factor w/ 3 levels "mixed","boys",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ schavg  : num  0.166 0.166 0.166 0.166 0.166 ...
 $ vr      : Factor w/ 3 levels "bottom 25%","mid 50%",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ intake  : Factor w/ 3 levels "bottom 25%","mid 50%",..: 1 2 3 2 2 1 3 2 2 3 ...
 $ standLRT: num   0.619  0.206 -1.365  0.206  0.371 ...
 $ sex     : Factor w/ 2 levels "F","M": 1 1 2 1 1 2 2 2 1 2 ...
 $ type    : Factor w/ 2 levels "Mxd","Sngl": 1 1 1 1 1 1 1 1 1 1 ...
 $ student : Factor w/ 650 levels "1","2","3","4",..: 143 145 142 141 138 155 158 115 117 113 ...
 $ ids     : Factor w/ 4055 levels "1:1","1:4","1:6",..: 48 49 47 46 45 50 51 39 40 38 ...
\end{Soutput}
\end{Schunk}
Notice that there are 4059 observations but only 4055 unique levels of
student within school.  We can check the ones that are duplicated
\begin{Schunk}
\begin{Sinput}
> Exam$ids[which(duplicated(Exam$ids))]
\end{Sinput}
\begin{Soutput}
[1] 43:86 50:39 52:2  52:21
4055 Levels: 1:1 1:4 1:6 1:7 1:13 1:14 1:16 1:17 1:19 1:22 1:27 ... 65:155
\end{Soutput}
\end{Schunk}

One of these duplicated cases is particularly interesting.  One of the
students with the duplicated student id 86 in school 43 is the only
male student in this mixed school.  This is probably a case of a
misrecorded school.



\section{Three-level Normal Models}
\label{sec:three-level}

These results are from the 1997 A-level Chemistry exam.  The
\code{school} is nested in \code{lea} (local education authority) and
has unique levels for each of the 2410 schools.  It is a good practice
to make the nesting explicit by specifying the grouping factors as the
`outer' factor, \code{lea} in this case, and the interaction of the
outer and inner factors, \code{lea:school} or \code{school:lea} in
this case.  This will ensure unique levels for each \code{school}
within \code{lea} combination.

To fit the model \code{mC2} we increase the number of EM iterations
from its default of 20 to 40.  Without this change the current version
of the \code{optim} function in \RR{} will declare convergence to an
incorrect optimum.  By increasing the number of EM iterations we are
able to get closer to the optimum before calling \code{optim} and
converge to the correct value.  The optim function will be patched so
this change will not be needed in future versions of \RR{}.

Data from the 1997 A-level Chemistry exam are available as \code{Chem97}.

\begin{Schunk}
\begin{Sinput}
> str(Chem97)
\end{Sinput}
\begin{Soutput}
`data.frame':	31022 obs. of  8 variables:
 $ lea      : Factor w/ 131 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ school   : Factor w/ 2410 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ student  : Factor w/ 31022 levels "1","2","3","4",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ score    : num  4 10 10 10 8 10 6 8 4 10 ...
 $ gender   : Factor w/ 2 levels "M","F": 2 2 2 2 2 2 2 2 2 2 ...
 $ age      : num  3 -3 -4 -2 -1 4 1 4 3 0 ...
 $ gcsescore: num  6.62 7.62 7.25 7.50 6.44 ...
 $ gcsecnt  : num  0.339 1.339 0.964 1.214 0.158 ...
\end{Soutput}
\begin{Sinput}
> system.time(mC1 <- lmer(score ~ 1 + (1 | lea:school) + (1 | 
+     lea), Chem97), gc = TRUE)
\end{Sinput}
\begin{Soutput}
[1] 3.52 0.05 3.57 0.00 0.00
\end{Soutput}
\begin{Sinput}
> summary(mC1)
\end{Sinput}
\begin{Soutput}
Linear mixed-effects model fit by REML
Formula: score ~ 1 + (1 | lea:school) + (1 | lea) 
   Data: Chem97 
      AIC      BIC   logLik deviance REMLdeviance
 157881.8 157915.2 -78936.9 157869.9     157873.8
Random effects:
 Groups     Name        Variance Std.Dev.
 lea:school (Intercept) 2.74981  1.6583  
 lea        (Intercept) 0.15343  0.3917  
 Residual               8.51591  2.9182  
# of obs: 31022, groups: lea:school, 2410; lea, 131

Fixed effects:
              Estimate Std. Error    DF t value  Pr(>|t|)
(Intercept) 5.3189e+00 5.8108e-02 31021  91.536 < 2.2e-16
\end{Soutput}
\begin{Sinput}
> system.time(mC2 <- lmer(score ~ gcsecnt + (1 | school) + 
+     (1 | lea), Chem97, control = list(niterEM = 40)), gc = TRUE)
\end{Sinput}
\begin{Soutput}
[1] 1.59 0.01 1.59 0.00 0.00
\end{Soutput}
\begin{Sinput}
> summary(mC2)
\end{Sinput}
\begin{Soutput}
Linear mixed-effects model fit by REML
Formula: score ~ gcsecnt + (1 | school) + (1 | lea) 
   Data: Chem97 
      AIC      BIC    logLik deviance REMLdeviance
 141707.2 141748.9 -70848.58 141685.8     141697.2
Random effects:
 Groups   Name        Variance Std.Dev.
 school   (Intercept) 1.163183 1.07851 
 lea      (Intercept) 0.020849 0.14439 
 Residual             5.153861 2.27021 
# of obs: 31022, groups: school, 2410; lea, 131

Fixed effects:
              Estimate Std. Error    DF t value  Pr(>|t|)
(Intercept) 5.6377e+00 3.2353e-02 31020  174.26 < 2.2e-16
gcsecnt     2.4726e+00 1.6907e-02 31020  146.25 < 2.2e-16

Correlation of Fixed Effects:
        (Intr)
gcsecnt 0.056 
\end{Soutput}
\end{Schunk}


\section{Two-level models for binary data}
\label{sec:TwolevelBinary}

The data frame \code{Contraception} provides data from the
Bangladesh fertility survey.
\begin{Schunk}
\begin{Sinput}
> str(Contraception)
\end{Sinput}
\begin{Soutput}
`data.frame':	1934 obs. of  6 variables:
 $ woman   : Factor w/ 1934 levels "1","2","3","4",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ district: Factor w/ 60 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ use     : Factor w/ 2 levels "N","Y": 1 1 1 1 1 1 1 1 1 1 ...
 $ livch   : Factor w/ 4 levels "0","1","2","3+": 4 1 3 4 1 1 4 4 2 4 ...
 $ age     : num   18.44  -5.56   1.44   8.44 -13.56 ...
 $ urban   : Factor w/ 2 levels "N","Y": 2 2 2 2 2 2 2 2 2 2 ...
\end{Soutput}
\begin{Sinput}
> summary(Contraception[, -1])
\end{Sinput}
\begin{Soutput}
    district    use      livch         age             urban   
 14     : 118   N:1175   0 :530   Min.   :-13.560000   N:1372  
 1      : 117   Y: 759   1 :356   1st Qu.: -7.559900   Y: 562  
 46     :  86            2 :305   Median : -1.559900           
 25     :  67            3+:743   Mean   :  0.002198           
 6      :  65                     3rd Qu.:  6.440000           
 30     :  61                     Max.   : 19.440000           
 (Other):1420                                                  
\end{Soutput}
\begin{Sinput}
> system.time(mB1 <- lmer(use ~ urban + age + livch + (1 | 
+     district), Contraception, family = binomial))
\end{Sinput}
\begin{Soutput}
[1] 0.74 0.01 0.75 0.00 0.00
\end{Soutput}
\begin{Sinput}
> summary(mB1)
\end{Sinput}
\begin{Soutput}
Generalized linear mixed model fit using PQL 
Formula: use ~ urban + age + livch + (1 | district) 
   Data: Contraception 
 Family: binomial ( logit link)
      AIC      BIC    logLik deviance
 2429.664 2474.203 -1206.832 2413.664
Random effects:
 Groups   Name        Variance Std.Dev.
 district (Intercept) 0.20917  0.45735 
 Residual             0.97208  0.98594 
# of obs: 1934, groups: district, 60

Estimated scale (compare to 1)  0.9844111 

Fixed effects:
              Estimate Std. Error  z value  Pr(>|z|)
(Intercept) -1.6606460  0.1452147 -11.4358 < 2.2e-16
urbanY       0.7193097  0.1183317   6.0788 1.211e-09
age         -0.0261558  0.0078152  -3.3468 0.0008176
livch1       1.0921026  0.1565011   6.9782 2.989e-12
livch2       1.3545533  0.1729641   7.8314 4.824e-15
livch3+      1.3241531  0.1773558   7.4661 8.262e-14

Correlation of Fixed Effects:
        (Intr) urbanY age    livch1 livch2
urbanY  -0.300                            
age      0.446 -0.046                     
livch1  -0.589  0.059 -0.211              
livch2  -0.631  0.094 -0.378  0.488       
livch3+ -0.748  0.098 -0.674  0.539  0.619
\end{Soutput}
\begin{Sinput}
> system.time(mB2 <- lmer(use ~ urban + age + livch + (1 | 
+     district), Contraception, family = binomial, method = "Laplace"))
\end{Sinput}
\begin{Soutput}
[1] 13.95  0.02 14.00  0.00  0.00
\end{Soutput}
\begin{Sinput}
> summary(mB2)
\end{Sinput}
\begin{Soutput}
Generalized linear mixed model fit using Laplace 
Formula: use ~ urban + age + livch + (1 | district) 
   Data: Contraception 
 Family: binomial ( logit link)
      AIC      BIC    logLik deviance
 2429.616 2474.154 -1206.808 2413.616
Random effects:
 Groups   Name        Variance Std.Dev.
 district (Intercept) 0.20917  0.45735 
 Residual             0.97208  0.98594 
# of obs: 1934, groups: district, 60

Estimated scale (compare to 1)  0.9844111 

Fixed effects:
              Estimate Std. Error  z value  Pr(>|z|)
(Intercept) -1.6897122  0.1452147 -11.6360 < 2.2e-16
urbanY       0.7329916  0.1183317   6.1944 5.852e-10
age         -0.0265952  0.0078152  -3.4030 0.0006665
livch1       1.1091850  0.1565011   7.0874 1.367e-12
livch2       1.3763970  0.1729641   7.9577 1.753e-15
livch3+      1.3452373  0.1773558   7.5850 3.326e-14

Correlation of Fixed Effects:
        (Intr) urbanY age    livch1 livch2
urbanY  -0.300                            
age      0.446 -0.046                     
livch1  -0.589  0.059 -0.211              
livch2  -0.631  0.094 -0.378  0.488       
livch3+ -0.748  0.098 -0.674  0.539  0.619
\end{Soutput}
\begin{Sinput}
> system.time(mB3 <- lmer(use ~ urban + age + livch + (urban | 
+     district), Contraception, family = binomial))
\end{Sinput}
\begin{Soutput}
[1] 1.33 0.00 1.33 0.00 0.00
\end{Soutput}
\begin{Sinput}
> summary(mB3)
\end{Sinput}
\begin{Soutput}
Generalized linear mixed model fit using PQL 
Formula: use ~ urban + age + livch + (urban | district) 
   Data: Contraception 
 Family: binomial ( logit link)
      AIC      BIC    logLik deviance
 2419.121 2474.795 -1199.561 2399.121
Random effects:
 Groups   Name        Variance Std.Dev. Corr   
 district (Intercept) 0.37047  0.60866         
          urbanY      0.63772  0.79858  -0.793 
 Residual             0.95546  0.97747         
# of obs: 1934, groups: district, 60

Estimated scale (compare to 1)  0.9759564 

Fixed effects:
              Estimate Std. Error  z value  Pr(>|z|)
(Intercept) -1.6665200  0.1572532 -10.5977 < 2.2e-16
urbanY       0.7914232  0.1681257   4.7073 2.510e-06
age         -0.0258502  0.0079082  -3.2688   0.00108
livch1       1.0987723  0.1580051   6.9540 3.550e-12
livch2       1.3342511  0.1745854   7.6424 2.132e-14
livch3+      1.3227367  0.1795440   7.3672 1.743e-13

Correlation of Fixed Effects:
        (Intr) urbanY age    livch1 livch2
urbanY  -0.481                            
age      0.416 -0.036                     
livch1  -0.548  0.038 -0.211              
livch2  -0.586  0.068 -0.378  0.487       
livch3+ -0.695  0.062 -0.674  0.537  0.616
\end{Soutput}
\begin{Sinput}
> system.time(mB4 <- lmer(use ~ urban + age + livch + (urban | 
+     district), Contraception, family = binomial, method = "Laplace"))
\end{Sinput}
\begin{Soutput}
[1] 26.05  0.03 26.10  0.00  0.00
\end{Soutput}
\begin{Sinput}
> summary(mB4)
\end{Sinput}
\begin{Soutput}
Generalized linear mixed model fit using Laplace 
Formula: use ~ urban + age + livch + (urban | district) 
   Data: Contraception 
 Family: binomial ( logit link)
      AIC     BIC    logLik deviance
 2419.016 2474.69 -1199.508 2399.016
Random effects:
 Groups   Name        Variance Std.Dev. Corr   
 district (Intercept) 0.37047  0.60866         
          urbanY      0.63772  0.79858  -0.793 
 Residual             0.95546  0.97747         
# of obs: 1934, groups: district, 60

Estimated scale (compare to 1)  0.9759564 

Fixed effects:
              Estimate Std. Error  z value  Pr(>|z|)
(Intercept) -1.7118541  0.1572532 -10.8860 < 2.2e-16
urbanY       0.8152811  0.1681257   4.8492 1.239e-06
age         -0.0265209  0.0079082  -3.3536 0.0007977
livch1       1.1256978  0.1580051   7.1244 1.045e-12
livch2       1.3683423  0.1745854   7.8377 4.590e-15
livch3+      1.3548081  0.1795440   7.5458 4.494e-14

Correlation of Fixed Effects:
        (Intr) urbanY age    livch1 livch2
urbanY  -0.481                            
age      0.416 -0.036                     
livch1  -0.548  0.038 -0.211              
livch2  -0.586  0.068 -0.378  0.487       
livch3+ -0.695  0.062 -0.674  0.537  0.616
\end{Soutput}
\end{Schunk}


\section{Growth curve model for repeated measures data}
\label{sec:GrowthCurve}

\begin{Schunk}
\begin{Sinput}
> str(Oxboys)
\end{Sinput}
\begin{Soutput}
`data.frame':	234 obs. of  4 variables:
 $ Subject : Factor w/ 26 levels "1","10","11",..: 1 1 1 1 1 1 1 1 1 12 ...
 $ age     : num  -1.0000 -0.7479 -0.4630 -0.1643 -0.0027 ...
 $ height  : num  140 143 145 147 148 ...
 $ Occasion: Factor w/ 9 levels "1","2","3","4",..: 1 2 3 4 5 6 7 8 9 1 ...
 - attr(*, "ginfo")=List of 7
  ..$ formula     :Class 'formula' length 3 height ~ age | Subject
  .. .. ..- attr(*, ".Environment")=length 8 <environment> 
  ..$ order.groups: logi TRUE
  ..$ FUN         :function (x)  
  .. ..- attr(*, "source")= chr "function (x) max(x, na.rm = TRUE)"
  ..$ outer       : NULL
  ..$ inner       : NULL
  ..$ labels      :List of 2
  .. ..$ age   : chr "Centered age"
  .. ..$ height: chr "Height"
  ..$ units       :List of 1
  .. ..$ height: chr "(cm)"
\end{Soutput}
\begin{Sinput}
> system.time(mX1 <- lmer(height ~ age + I(age^2) + I(age^3) + 
+     I(age^4) + (age + I(age^2) | Subject), Oxboys), gc = TRUE)
\end{Sinput}
\begin{Soutput}
[1] 0.43 0.00 0.43 0.00 0.00
\end{Soutput}
\begin{Sinput}
> summary(mX1)
\end{Sinput}
\begin{Soutput}
Linear mixed-effects model fit by REML
Formula: height ~ age + I(age^2) + I(age^3) + I(age^4) + (age + I(age^2) |      Subject) 
   Data: Oxboys 
      AIC     BIC    logLik deviance REMLdeviance
 651.9081 693.372 -313.9541 625.3593     627.9081
Random effects:
 Groups   Name        Variance Std.Dev. Corr        
 Subject  (Intercept) 64.03130 8.00196              
          age          2.86408 1.69236  0.614       
          I(age^2)     0.67428 0.82115  0.215 0.658 
 Residual              0.21738 0.46624              
# of obs: 234, groups: Subject, 26

Fixed effects:
             Estimate Std. Error  DF t value  Pr(>|t|)
(Intercept) 149.01887    1.57032 229 94.8971 < 2.2e-16
age           6.17418    0.35650 229 17.3190 < 2.2e-16
I(age^2)      1.12823    0.35144 229  3.2103  0.001516
I(age^3)      0.45385    0.16246 229  2.7937  0.005653
I(age^4)     -0.37690    0.30018 229 -1.2556  0.210554

Correlation of Fixed Effects:
         (Intr) age    I(g^2) I(g^3)
age       0.572                     
I(age^2)  0.076  0.264              
I(age^3) -0.001 -0.340  0.025       
I(age^4)  0.021  0.016 -0.857 -0.021
\end{Soutput}
\begin{Sinput}
> system.time(mX2 <- lmer(height ~ poly(age, 4) + (age + I(age^2) | 
+     Subject), Oxboys), gc = TRUE)
\end{Sinput}
\begin{Soutput}
[1] 0.41 0.00 0.40 0.00 0.00
\end{Soutput}
\begin{Sinput}
> summary(mX2)
\end{Sinput}
\begin{Soutput}
Linear mixed-effects model fit by REML
Formula: height ~ poly(age, 4) + (age + I(age^2) | Subject) 
   Data: Oxboys 
      AIC      BIC    logLik deviance REMLdeviance
 640.8686 682.3324 -308.4343 625.3593     616.8686
Random effects:
 Groups   Name        Variance Std.Dev. Corr        
 Subject  (Intercept) 64.03114 8.00195              
          age          2.86407 1.69236  0.614       
          I(age^2)     0.67428 0.82115  0.215 0.658 
 Residual              0.21738 0.46624              
# of obs: 234, groups: Subject, 26

Fixed effects:
               Estimate Std. Error  DF t value  Pr(>|t|)
(Intercept)   149.51976    1.59026 229 94.0222 < 2.2e-16
poly(age, 4)1  64.54095    3.32780 229 19.3945 < 2.2e-16
poly(age, 4)2   4.20322    1.02361 229  4.1063 5.597e-05
poly(age, 4)3   1.29077    0.46628 229  2.7682  0.006098
poly(age, 4)4  -0.58547    0.46630 229 -1.2556  0.210554

Correlation of Fixed Effects:
            (Intr) p(,4)1 p(,4)2 p(,4)3
poly(ag,4)1 0.631                      
poly(ag,4)2 0.230  0.583               
poly(ag,4)3 0.000  0.000  0.000        
poly(ag,4)4 0.000  0.000  0.000  0.000 
\end{Soutput}
\end{Schunk}

\section{Cross-classification model}
\label{sec:CrossClassified}

\begin{Schunk}
\begin{Sinput}
> str(ScotsSec)
\end{Sinput}
\begin{Soutput}
`data.frame':	3435 obs. of  6 variables:
 $ verbal : num  11 0 -14 -6 -30 -17 -17 -11 -9 -19 ...
 $ attain : num  10 3 2 3 2 2 4 6 4 2 ...
 $ primary: Factor w/ 148 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ sex    : Factor w/ 2 levels "M","F": 1 2 1 1 2 2 2 1 1 1 ...
 $ social : num  0 0 0 20 0 0 0 0 0 0 ...
 $ second : Factor w/ 19 levels "1","2","3","4",..: 9 9 9 9 9 9 1 1 9 9 ...
\end{Soutput}
\begin{Sinput}
> system.time(mS1 <- lmer(attain ~ sex + (1 | primary) + (1 | 
+     second), ScotsSec), gc = TRUE)
\end{Sinput}
\begin{Soutput}
[1] 0.22 0.00 0.22 0.00 0.00
\end{Soutput}
\begin{Sinput}
> summary(mS1)
\end{Sinput}
\begin{Soutput}
Linear mixed-effects model fit by REML
Formula: attain ~ sex + (1 | primary) + (1 | second) 
   Data: ScotsSec 
      AIC      BIC    logLik deviance REMLdeviance
 17137.91 17168.62 -8563.956 17123.49     17127.91
Random effects:
 Groups   Name        Variance Std.Dev.
 primary  (Intercept) 1.10962  1.0534  
 second   (Intercept) 0.36966  0.6080  
 Residual             8.05511  2.8382  
# of obs: 3435, groups: primary, 148; second, 19

Fixed effects:
              Estimate Std. Error   DF t value  Pr(>|t|)
(Intercept) 5.2552e+00 1.8432e-01 3433 28.5107 < 2.2e-16
sexF        4.9851e-01 9.8255e-02 3433  5.0737 4.109e-07

Correlation of Fixed Effects:
     (Intr)
sexF -0.264
\end{Soutput}
\end{Schunk}

\end{document}
